### ISSUE TITLE
$this->stream is undefined

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/lib-gedcom#9]
https://github.com/fisharebest/lib-gedcom/blob/d5367bbd4bf94094c567c40c62277d6fb30c285b/src/Filters/AbstractGedcomFilter.php#L51

https://github.com/fisharebest/lib-gedcom/blob/d5367bbd4bf94094c567c40c62277d6fb30c285b/src/Filters/AbstractGedcomFilter.php#L60

**Comment by fisharebest** [comment]
The `->stream` attribute is missing from the PHPstorm stub functions.  It really does exist in the PHP code!  Perhaps raise a bug with JetBrains?

**Comment by magicsunday** [comment]
Ah ok, thank. I didn't know that: https://bugs.php.net/bug.php?id=73586&edit=3
